#: kivy 2.0.0

<MainScreen>:

    FloatLayout:
        pos: 0, 0
        size: root.width, root.height

        Button:
            text: "Button 1"
            pos_hint: {'x': 0.1, 'y': 0.1}
            size_hint: None, None
            size: 300, 200

        Button:
            text: "Button 2"
            pos_hint: {'x': 0.1, 'y': 0.6}
            size_hint: None, None
            size: 300, 200